name: Merge Bot

on:
  pull_request:
    types:
      - labeled

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge
    steps:
    - name: Integration check
      uses: squalrus/merge-bot@v0.2.0
      with:
        token: ${{ secrets.HIGHCHARTTEST }}
        test: true
        reviewers: false
        labels: automated pr
        checks: labels
        method: squash
